### ISSUE TITLE
File not found bug

### ISSUE THREAD

**Issue by MrSonicOSG** [k4yt3x/video2x#189]
When using Anime4K as the backend is tries to redirect to a different user folder on the c drive than what is available, in this case its directing to the developer's user folders 
![image](https://user-images.githubusercontent.com/56853459/72393061-b9346300-36ff-11ea-8180-f23285229098.png)

**Comment by k4yt3x** [comment]
What version of the setup scrip are you using?

**Comment by MrSonicOSG** [comment]
the most recent one, i looked into it and it seems its caused by the file locations in the config file not being relative locations, but specific ones. i fixed the issue by changing the file path manually in the config file

**Comment by MrSonicOSG** [comment]
oh wait, i just realised what you meant, i ran the lite version installer

**Comment by k4yt3x** [comment]
Is it solved now?

**Comment by MrSonicOSG** [comment]
when i manually fixed it yeah it works now, but its still an issue in v 2.10.00 of the releases

**Comment by k4yt3x** [comment]
This should be fixed in the newest release. Please confirm.
