### ISSUE TITLE
CLI fails to execute upscaling driver

### ISSUE THREAD

**Issue by GitGerby** [k4yt3x/video2x#412]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:  4.7.0
- **Upscaler version**:
- **GUI version**:
- **CLI version**:  4.3.1

## Symptom
CLI fails to execute upscaler after extracting frames.

## Error Log or Screenshots

```
Traceback (most recent call last):
  File "video2x.py", line 271, in <module>
  File "upscaler.py", line 802, in run
  File "upscaler.py", line 692, in run
  File "upscaler.py", line 325, in _upscale_frames
  File "C:\Users\<user>\AppData\Local\Temp\_MEI69082\wrappers\waifu2x_ncnn_vulkan.py", line 85, in upscale
    os.chdir(pathlib.Path(self.driver_settings['path']).parent)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies\\waifu2x-ncnn-vulkan'
```

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Hmmmm that's interesting. Does the GUI run just fine?

**Comment by GitGerby** [comment]
The GUI does execute the driver but it results in a different error; working on tracking that down if there's a driver issue?
```
kCreateInstance failed -9
vkCreateInstance failed -9
invalid gpu device
[!] ERROR: Subprocess 6196 exited with code 4294967295
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
2020-11-21 03:02:15.324984 [+] INFO: Killing progress monitor
Processing: sample_input.mp4 (pass 1/1):   0%|                                                 | 0/456 [00:04<?, ?it/s]
2020-11-21 03:02:15.856245 [+] INFO: Killing upscaled image cleaner
Cleaning up cache directory: C:\Users\<user>\AppData\Local\Temp\2\video2x\tmpa71llagq
Cleaning up cache directory: C:\Users\<user>\AppData\Local\Temp\2\video2x\tmpgg5kw84x
Cleaning up cache directory: C:\Users\<user>\AppData\Local\Temp\2\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 802, in run
  File "upscaler.py", line 692, in run
  File "upscaler.py", line 347, in _upscale_frames
  File "upscaler.py", line 339, in _upscale_frames
  File "upscaler.py", line 409, in _wait
  File "upscaler.py", line 393, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\<user>\\Desktop\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe', '-n', '2', '-s', '2', '-t', '32', '-m', 'C:\\Users\\<user>\\Desktop\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '1', '-j', '1:1:1', '-i', 'C:\\Users\\<user>\\AppData\\Local\\Temp\\2\\video2x\\tmpa71llagq', '-o', 'C:\\Users\\<user>\\AppData\\Local\\Temp\\2\\video2x\\tmpgg5kw84x']' returned non-zero exit status 4294967295.
```

**Comment by GitGerby** [comment]
Interestingly here the caffe driver works; wondering if there's something strange with the nvidia drivers on this cloud instance?

**Comment by GitGerby** [comment]
For those looking at this in the future the issue was with nVidia GRID; the feature needed to be enabled on the Compute Engine instance in GCP and the specific GRID driver needed to be installed for Vulkan to operate.

**Comment by GitGerby** [comment]
Typed too soon; while running the vulkan driver by hand now functions running the video2x CLI still results in the same error; GUI now works. I'm confused.

**Comment by GitGerby** [comment]
Have now confirmed the issue on a physical host that I've been working with for months with the GUI. Seems something is up with how the CLI version is determining its location to create the call to the vulkan upscaler.

**Comment by k4yt3x** [comment]
I remember I programmed the GUI to always expand all paths into absolute paths. I'll have to check if the CLI isn't constructing the paths properly.

**Comment by k4yt3x** [comment]
There has been a lot of changes in the past few versions.
Could you please verify that this issue still exists in the newest release?

**Comment by GitGerby** [comment]
Testing release 4.8.1 now; though for what it's worth the bundled CLI version has a banner saying 4.3.1

**Comment by GitGerby** [comment]
```
2021-01-28 20:17:06.440265 [+] INFO: Executing: dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i X:\other\upscale\ditch.gif -pix_fmt rgb24 x:\other\upscale\cache\tmpztgpmlhd\extracted_%0d.png
2021-01-28 20:17:06.455289 [+] INFO: Main process waiting for subprocesses to exit
2021-01-28 20:17:13.088962 [+] INFO: Subprocess 7304 exited with code 0
[+] INFO: Starting to upscale extracted frames
Cleaning up cache directory: x:\other\upscale\cache\tmpztgpmlhd
Cleaning up cache directory: x:\other\upscale\cache\tmpl1sc2v2z
Cleaning up cache directory: x:\other\upscale\cache
```
Very strange behavior now; hangs here.

**Comment by k4yt3x** [comment]
Hmmm what? Do you have any error logs or did it not trip an exception?

**Comment by GitGerby** [comment]
That's where it stopped. after about 5 minutes I hit `ctrl-c` and stopped
execution. I didn't see any evidence that waifu2x-ncnn-vulkan was ever
invoked.

**Comment by k4yt3x** [comment]
That's bizarre... no output at all?
I don't have any good ideas at the moment.

**Comment by michaelbonadio** [comment]
on version 4.8.1 CLI, I get the original error 
```[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 342, in <module>
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 849, in run
  File "upscaler.py", line 391, in _upscale_frames
  File "C:\Users\MICHAE~1\AppData\Local\Temp\_MEI510562\wrappers\waifu2x_caffe.py", line 90, in upscale
    os.chdir(pathlib.Path(self.driver_settings["path"]).parent)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies\\waifu2x-caffe'```

The GUI does not seem to have the same issue. 

[video2x_d94dhlki.log](https://github.com/k4yt3x/video2x/files/6743558/video2x_d94dhlki.log)

**Comment by jdinh1** [comment]
I'm getting the same error as @michaelbonadio also on v4.8.1 (v4.3.1 CLI). For those that encounter this issue, a temporary fix was to provide the absolute path to the drivers inside `video2x.yaml`, i.e.

```
waifu2x_caffe:
  path: 'C:\Users\ItsMe\Desktop\video2x-4.8.1-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui'
...
```

**Comment by GameTec-live** [comment]
i have the same error too on v4.8.1.

**Comment by k4yt3x** [comment]
@GameTec-live post your error logs

**Comment by GameTec-live** [comment]
its the same as the others, it cant find the dependencir of the realncnn shader, replaceing it in the yaml with an absolute path works

**Comment by k4yt3x** [comment]
It's very rare that I get reports like this. Out of the hundreds of thousands of downloads, I only get a couple of people that encounter this problem. I suspect it's related to your locale or something else about your environment. What locale and OS version are you running it in?

**Comment by GameTec-live** [comment]
windows 11 pro, 21H2
AMD Ryzen Threadripper 1900X 8-Core Processor     3.80 GHz
32,0 GB RAM
64 Bit
And the locale would be German

**Comment by GameTec-live** [comment]
is there a nightly windows build available? maybe i can try that one?

**Comment by k4yt3x** [comment]
> is there a nightly windows build available?

There isn't right now. 4.8.* is no longer maintained as I no longer have the dev environment. 5.0.0 doesn't have pre-compiled binaries for Windows just yet. Maybe try temporarily changing your locale to English and see what happens?

**Comment by flopezre** [comment]
Hi i have a similar error:
![error](https://user-images.githubusercontent.com/4932575/197679182-7aad812e-b5bb-4e85-b0e9-f9c69b919586.png)

Cheers

**Comment by TechniumUnlimited** [comment]
I have this error right now, 
`[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 342, in <module>
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 849, in run
  File "upscaler.py", line 391, in _upscale_frames
  File "C:\Users\Technium\AppData\Local\Temp\_MEI51922\wrappers\waifu2x_ncnn_vulkan.py", line 92, in upscale
    os.chdir(pathlib.Path(self.driver_settings["path"]).parent)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies\\waifu2x-ncnn-vulkan'`

**Comment by SapoKR** [comment]
The above error occurred and it was resolved by attaching .exe to the path of waifu2x_ncnn_vulkan in the video2x.yaml file.

**Comment by SapoKR** [comment]
change path "dependencies\waifu2x-ncnn-vulkan" -> "dependencies\waifu2x-ncnn-vulkan.exe"

![image](https://user-images.githubusercontent.com/56115521/212284636-2a237e10-cfbd-402a-b26e-1ba6cc3002c2.png)

**Comment by doktoil-makresh** [comment]
Thank you @SapoKR for your detailled explanations.
However, this is still not working here.
My path is a bit different:
waifu2x_ncnn_vulkan:
  path: 'dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan'
I tried changing it to 
waifu2x_ncnn_vulkan:
  path: 'dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan.exe'
and despite the file exists, I'm receiving the error.

**Comment by tts2** [comment]
> Thank you @SapoKR for your detailled explanations.
However, this is still not working here.
My path is a bit different:
waifu2x_ncnn_vulkan:
path: 'dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan'
I tried changing it to
waifu2x_ncnn_vulkan:
path: 'dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan.exe'
and despite the file exists, I'm receiving the error.
You need to change the path to absolute
path: 'C:\\python\\Project\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe'
