### ISSUE TITLE
Output video always black

### ISSUE THREAD

**Issue by Ciellent** [k4yt3x/video2x#77]
video2x.exe -m gpu -r 2 -i C:\Users\REDACTED\Desktop\1\1.mp4 -o C:\Users\REDACTED\Desktop\2\1.mp4

 is what i input into the cmd and when it finishes the video is always black right to the end but the audio is working fine.

**Comment by Ciellent** [comment]
`Microsoft Windows [Version 10.0.17134.648]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full

C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full>video2x.exe -m gpu -r 2 -i C:\Users\REDACTED\Desktop\1\1.mp4 -o C:\Users\REDACTED\Desktop\2\1.mp4
__      __  _       _                  ___   __   __
\ \    / / (_)     | |                |__ \  \ \ / /
 \ \  / /   _    __| |   ___    ___      ) |  \ V /
  \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
   \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
    \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

               Video2X Video Enlarger

                   Version 2.7.0

[!] WARNING: Each waifu2x-caffe thread will require up to 2.5 GB of system memory
[!] WARNING: You demanded 5 threads to be created, but you only have 10.3906 GB system memory available
[!] WARNING: 12.5 GB of system memory is recommended for 5 threads
[!] WARNING: With your current amount of system memory available, 4 threads is recommended
[?] USER: Change to the recommended value? [Y/n]:
[!] WARNING: You might have insufficient amount of GPU memory available to run this program (3.2177734375 GB)
[!] WARNING: Proceed with caution
[?] USER: Reduce number of threads to avoid crashing? [Y/n]:
[!] WARNING: Specified cache folder/directory C:\Users\REDACTED\AppData\Local\Temp\video2x does not exist
[?] USER: Create folder/directory? [Y/n]:
[+] INFO: C:\Users\REDACTED\AppData\Local\Temp\video2x created
[+] INFO: Upscaling single video file: C:\Users\REDACTED\Desktop\1\1.mp4
2019-04-09 23:33:04.093395 [+] INFO: Extracted frames are being saved to: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmpy65_boll
2019-04-09 23:33:04.094396 [+] INFO: Upscaled frames are being saved to: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt
2019-04-09 23:33:04.095397 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-i', 'C:\\Users\\REDACTED\\Desktop\\1\\1.mp4', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmpy65_boll\\extracted_%0d.png', '-hwaccel', 'auto', '-y']
ffmpeg version N-93485-g5282cbae61 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.106 / 58. 47.106
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Trailing options were found on the commandline.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\REDACTED\Desktop\1\1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2019-02-08T01:47:01.000000Z
  Duration: 00:00:19.07, start: 0.000000, bitrate: 1997 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 426x240, 1659 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmpy65_boll\extracted_%0d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf58.26.101
    Stream #0:0(eng): Video: png, rgb24, 426x240, q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : Lavc58.47.106 png
frame=  456 fps=153 q=-0.0 Lsize=N/A time=00:00:19.01 bitrate=N/A speed=6.37x
video:73181kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-04-09 23:33:07.201359 [+] INFO: Executing: C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\Users\REDACTED\Desktop\1\1.mp4
[+] INFO: Framerate: 23.976023976023978
[+] INFO: Starting to upscale extracted images
2019-04-09 23:33:07.787089 [+] INFO: Starting upscaled image cleaner
2019-04-09 23:33:07.789089 [+] INFO: [upscaler] Thread 0 started
2019-04-09 23:33:07.790089 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_ratio', '2.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmpy65_boll\\0', '--output_path', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt']
Upscaling Progress: 100%|###########################################################7| 454/456 [03:57<00:01,  1.98it/s]変換に成功しました

2019-04-09 23:37:06.632678 [+] INFO: [upscaler] Thread 0 exiting
2019-04-09 23:37:06.633678 [+] INFO: Killing upscaled image cleaner
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2019-04-09 23:37:07.454949 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-r', '23.976023976023978', '-s', '864x480', '-i', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt\\extracted_%d.png', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt\\no_audio.mp4', '-f', 'image2', '-vcodec', 'libx264', '-crf', '25', '-pix_fmt', 'yuv420p', '-hwaccel', 'auto', '-y']
ffmpeg version N-93485-g5282cbae61 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.106 / 58. 47.106
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Trailing options were found on the commandline.
Input #0, image2, from 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt\extracted_%d.png':
  Duration: 00:00:18.24, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 852x480, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 000002da9e6e54c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA3 BMI1
[libx264 @ 000002da9e6e54c0] profile High 4:4:4 Predictive, level 3.0, 4:4:4, 8-bit
[libx264 @ 000002da9e6e54c0] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=9 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt\no_audio.mp4':
  Metadata:
    encoder         : Lavf58.26.101
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv444p, 852x480, q=-1--1, 23.98 fps, 24k tbn, 23.98 tbc
    Metadata:
      encoder         : Lavc58.47.106 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=  456 fps= 95 q=-1.0 Lsize=     461kB time=00:00:18.89 bitrate= 199.7kbits/s speed=3.93x
video:454kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.354590%
[libx264 @ 000002da9e6e54c0] frame I:4     Avg QP:17.27  size: 20655
[libx264 @ 000002da9e6e54c0] frame P:114   Avg QP:19.57  size:  2361
[libx264 @ 000002da9e6e54c0] frame B:338   Avg QP:22.70  size:   334
[libx264 @ 000002da9e6e54c0] consecutive B-frames:  1.1%  0.0%  0.7% 98.2%
[libx264 @ 000002da9e6e54c0] mb I  I16..4: 22.9% 53.3% 23.9%
[libx264 @ 000002da9e6e54c0] mb P  I16..4:  1.7%  3.1%  1.5%  P16..4: 12.1%  3.1%  1.5%  0.0%  0.0%    skip:77.0%
[libx264 @ 000002da9e6e54c0] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  7.9%  0.5%  0.1%  direct: 0.1%  skip:91.1%  L0:43.6% L1:54.9% BI: 1.5%
[libx264 @ 000002da9e6e54c0] 8x8 transform intra:50.2% inter:83.9%
[libx264 @ 000002da9e6e54c0] coded y,u,v intra: 45.7% 20.9% 16.0% inter: 1.2% 0.3% 0.2%
[libx264 @ 000002da9e6e54c0] i16 v,h,dc,p: 22% 18%  4% 57%
[libx264 @ 000002da9e6e54c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 22% 14%  7%  5%  6%  5%  7%  6%
[libx264 @ 000002da9e6e54c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 18% 14%  7%  6%  9%  5%  8%  4%
[libx264 @ 000002da9e6e54c0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 000002da9e6e54c0] ref P L0: 63.8%  5.6% 20.3% 10.3%
[libx264 @ 000002da9e6e54c0] ref B L0: 79.4% 17.3%  3.3%
[libx264 @ 000002da9e6e54c0] ref B L1: 94.8%  5.2%
[libx264 @ 000002da9e6e54c0] kb/s:195.43
[+] INFO: Conversion completed
[+] INFO: Migrating audio tracks and subtitles to upscaled video
2019-04-09 23:37:12.437878 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-i', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt\\no_audio.mp4', '-i', 'C:\\Users\\REDACTED\\Desktop\\1\\1.mp4', 'C:\\Users\\REDACTED\\Desktop\\2\\1.mp4', '-map', '-1:v?', '-c', 'copy', '-hwaccel', 'auto', '-y']
ffmpeg version N-93485-g5282cbae61 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.106 / 58. 47.106
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Trailing options were found on the commandline.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt\no_audio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.26.101
  Duration: 00:00:19.02, start: 0.000000, bitrate: 198 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 852x480, 195 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\REDACTED\Desktop\1\1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2019-02-08T01:47:01.000000Z
  Duration: 00:00:19.07, start: 0.000000, bitrate: 1997 kb/s
    Stream #1:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 426x240, 1659 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #1:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #1:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 000001f9d7fda240] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA3 BMI1
[libx264 @ 000001f9d7fda240] profile High 4:4:4 Predictive, level 3.0, 4:4:4, 8-bit
[libx264 @ 000001f9d7fda240] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=9 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\REDACTED\Desktop\2\1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.26.101
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv444p(progressive), 852x480, q=-1--1, 23.98 fps, 24k tbn, 23.98 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.47.106 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
      encoder         : Lavc58.47.106 aac
frame=  456 fps=152 q=-1.0 Lsize=     772kB time=00:00:19.02 bitrate= 332.5kbits/s speed=6.36x
video:457kB audio:301kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.880370%
[libx264 @ 000001f9d7fda240] frame I:4     Avg QP:15.08  size: 22212
[libx264 @ 000001f9d7fda240] frame P:115   Avg QP:17.82  size:  2367
[libx264 @ 000001f9d7fda240] frame B:337   Avg QP:21.97  size:   315
[libx264 @ 000001f9d7fda240] consecutive B-frames:  1.1%  0.9%  0.7% 97.4%
[libx264 @ 000001f9d7fda240] mb I  I16..4: 20.7% 54.0% 25.4%
[libx264 @ 000001f9d7fda240] mb P  I16..4:  1.6%  3.2%  1.4%  P16..4: 10.7%  3.2%  1.6%  0.0%  0.0%    skip:78.4%
[libx264 @ 000001f9d7fda240] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  7.6%  0.5%  0.1%  direct: 0.1%  skip:91.5%  L0:46.5% L1:52.1% BI: 1.5%
[libx264 @ 000001f9d7fda240] 8x8 transform intra:52.4% inter:85.5%
[libx264 @ 000001f9d7fda240] coded y,u,v intra: 47.9% 22.9% 17.5% inter: 1.1% 0.3% 0.2%
[libx264 @ 000001f9d7fda240] i16 v,h,dc,p: 23% 21%  6% 50%
[libx264 @ 000001f9d7fda240] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 31% 22% 14%  6%  4%  6%  4%  7%  6%
[libx264 @ 000001f9d7fda240] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 19% 13%  7%  6%  8%  5%  8%  4%
[libx264 @ 000001f9d7fda240] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 000001f9d7fda240] ref P L0: 65.5%  6.1% 18.3% 10.2%
[libx264 @ 000001f9d7fda240] ref B L0: 76.0% 21.1%  3.0%
[libx264 @ 000001f9d7fda240] ref B L1: 95.8%  4.2%
[libx264 @ 000001f9d7fda240] kb/s:196.47
[aac @ 000001f9d7a585c0] Qavg: 407.877
Cleaning up cache directory: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmpy65_boll
Cleaning up cache directory: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt
[+] INFO: Program completed, taking 251.68042 seconds

C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full>`

this is the entire cmd

**Comment by Ciellent** [comment]
```Microsoft Windows [Version 10.0.17134.648]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full

C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full>video2x.exe -m gpu -r 2 -i C:\Users\REDACTED\Desktop\1\1.mp4 -o C:\Users\REDACTED\Desktop\2\1.mp4
__      __  _       _                  ___   __   __
\ \    / / (_)     | |                |__ \  \ \ / /
 \ \  / /   _    __| |   ___    ___      ) |  \ V /
  \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
   \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
    \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

               Video2X Video Enlarger

                   Version 2.7.0

[!] WARNING: Each waifu2x-caffe thread will require up to 2.5 GB of system memory
[!] WARNING: You demanded 5 threads to be created, but you only have 10.3906 GB system memory available
[!] WARNING: 12.5 GB of system memory is recommended for 5 threads
[!] WARNING: With your current amount of system memory available, 4 threads is recommended
[?] USER: Change to the recommended value? [Y/n]:
[!] WARNING: You might have insufficient amount of GPU memory available to run this program (3.2177734375 GB)
[!] WARNING: Proceed with caution
[?] USER: Reduce number of threads to avoid crashing? [Y/n]:
[!] WARNING: Specified cache folder/directory C:\Users\REDACTED\AppData\Local\Temp\video2x does not exist
[?] USER: Create folder/directory? [Y/n]:
[+] INFO: C:\Users\REDACTED\AppData\Local\Temp\video2x created
[+] INFO: Upscaling single video file: C:\Users\REDACTED\Desktop\1\1.mp4
2019-04-09 23:33:04.093395 [+] INFO: Extracted frames are being saved to: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmpy65_boll
2019-04-09 23:33:04.094396 [+] INFO: Upscaled frames are being saved to: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt
2019-04-09 23:33:04.095397 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-i', 'C:\\Users\\REDACTED\\Desktop\\1\\1.mp4', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmpy65_boll\\extracted_%0d.png', '-hwaccel', 'auto', '-y']
ffmpeg version N-93485-g5282cbae61 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.106 / 58. 47.106
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Trailing options were found on the commandline.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\REDACTED\Desktop\1\1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2019-02-08T01:47:01.000000Z
  Duration: 00:00:19.07, start: 0.000000, bitrate: 1997 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 426x240, 1659 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmpy65_boll\extracted_%0d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf58.26.101
    Stream #0:0(eng): Video: png, rgb24, 426x240, q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : Lavc58.47.106 png
frame=  456 fps=153 q=-0.0 Lsize=N/A time=00:00:19.01 bitrate=N/A speed=6.37x
video:73181kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-04-09 23:33:07.201359 [+] INFO: Executing: C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\Users\REDACTED\Desktop\1\1.mp4
[+] INFO: Framerate: 23.976023976023978
[+] INFO: Starting to upscale extracted images
2019-04-09 23:33:07.787089 [+] INFO: Starting upscaled image cleaner
2019-04-09 23:33:07.789089 [+] INFO: [upscaler] Thread 0 started
2019-04-09 23:33:07.790089 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_ratio', '2.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmpy65_boll\\0', '--output_path', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt']
Upscaling Progress: 100%|###########################################################7| 454/456 [03:57<00:01,  1.98it/s]変換に成功しました

2019-04-09 23:37:06.632678 [+] INFO: [upscaler] Thread 0 exiting
2019-04-09 23:37:06.633678 [+] INFO: Killing upscaled image cleaner
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2019-04-09 23:37:07.454949 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-r', '23.976023976023978', '-s', '864x480', '-i', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt\\extracted_%d.png', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt\\no_audio.mp4', '-f', 'image2', '-vcodec', 'libx264', '-crf', '25', '-pix_fmt', 'yuv420p', '-hwaccel', 'auto', '-y']
ffmpeg version N-93485-g5282cbae61 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.106 / 58. 47.106
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Trailing options were found on the commandline.
Input #0, image2, from 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt\extracted_%d.png':
  Duration: 00:00:18.24, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 852x480, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 000002da9e6e54c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA3 BMI1
[libx264 @ 000002da9e6e54c0] profile High 4:4:4 Predictive, level 3.0, 4:4:4, 8-bit
[libx264 @ 000002da9e6e54c0] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=9 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt\no_audio.mp4':
  Metadata:
    encoder         : Lavf58.26.101
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv444p, 852x480, q=-1--1, 23.98 fps, 24k tbn, 23.98 tbc
    Metadata:
      encoder         : Lavc58.47.106 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=  456 fps= 95 q=-1.0 Lsize=     461kB time=00:00:18.89 bitrate= 199.7kbits/s speed=3.93x
video:454kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.354590%
[libx264 @ 000002da9e6e54c0] frame I:4     Avg QP:17.27  size: 20655
[libx264 @ 000002da9e6e54c0] frame P:114   Avg QP:19.57  size:  2361
[libx264 @ 000002da9e6e54c0] frame B:338   Avg QP:22.70  size:   334
[libx264 @ 000002da9e6e54c0] consecutive B-frames:  1.1%  0.0%  0.7% 98.2%
[libx264 @ 000002da9e6e54c0] mb I  I16..4: 22.9% 53.3% 23.9%
[libx264 @ 000002da9e6e54c0] mb P  I16..4:  1.7%  3.1%  1.5%  P16..4: 12.1%  3.1%  1.5%  0.0%  0.0%    skip:77.0%
[libx264 @ 000002da9e6e54c0] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  7.9%  0.5%  0.1%  direct: 0.1%  skip:91.1%  L0:43.6% L1:54.9% BI: 1.5%
[libx264 @ 000002da9e6e54c0] 8x8 transform intra:50.2% inter:83.9%
[libx264 @ 000002da9e6e54c0] coded y,u,v intra: 45.7% 20.9% 16.0% inter: 1.2% 0.3% 0.2%
[libx264 @ 000002da9e6e54c0] i16 v,h,dc,p: 22% 18%  4% 57%
[libx264 @ 000002da9e6e54c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 22% 14%  7%  5%  6%  5%  7%  6%
[libx264 @ 000002da9e6e54c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 18% 14%  7%  6%  9%  5%  8%  4%
[libx264 @ 000002da9e6e54c0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 000002da9e6e54c0] ref P L0: 63.8%  5.6% 20.3% 10.3%
[libx264 @ 000002da9e6e54c0] ref B L0: 79.4% 17.3%  3.3%
[libx264 @ 000002da9e6e54c0] ref B L1: 94.8%  5.2%
[libx264 @ 000002da9e6e54c0] kb/s:195.43
[+] INFO: Conversion completed
[+] INFO: Migrating audio tracks and subtitles to upscaled video
2019-04-09 23:37:12.437878 [+] INFO: Executing: ['C:\\Users\\REDACTED\\Desktop\\video2x-2.7.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-i', 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\video2x\\tmp4nmeeyqt\\no_audio.mp4', '-i', 'C:\\Users\\REDACTED\\Desktop\\1\\1.mp4', 'C:\\Users\\REDACTED\\Desktop\\2\\1.mp4', '-map', '-1:v?', '-c', 'copy', '-hwaccel', 'auto', '-y']
ffmpeg version N-93485-g5282cbae61 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.106 / 58. 47.106
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Trailing options were found on the commandline.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt\no_audio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.26.101
  Duration: 00:00:19.02, start: 0.000000, bitrate: 198 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 852x480, 195 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\REDACTED\Desktop\1\1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2019-02-08T01:47:01.000000Z
  Duration: 00:00:19.07, start: 0.000000, bitrate: 1997 kb/s
    Stream #1:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 426x240, 1659 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #1:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #1:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 000001f9d7fda240] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA3 BMI1
[libx264 @ 000001f9d7fda240] profile High 4:4:4 Predictive, level 3.0, 4:4:4, 8-bit
[libx264 @ 000001f9d7fda240] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=9 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\REDACTED\Desktop\2\1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.26.101
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv444p(progressive), 852x480, q=-1--1, 23.98 fps, 24k tbn, 23.98 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.47.106 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
      encoder         : Lavc58.47.106 aac
frame=  456 fps=152 q=-1.0 Lsize=     772kB time=00:00:19.02 bitrate= 332.5kbits/s speed=6.36x
video:457kB audio:301kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.880370%
[libx264 @ 000001f9d7fda240] frame I:4     Avg QP:15.08  size: 22212
[libx264 @ 000001f9d7fda240] frame P:115   Avg QP:17.82  size:  2367
[libx264 @ 000001f9d7fda240] frame B:337   Avg QP:21.97  size:   315
[libx264 @ 000001f9d7fda240] consecutive B-frames:  1.1%  0.9%  0.7% 97.4%
[libx264 @ 000001f9d7fda240] mb I  I16..4: 20.7% 54.0% 25.4%
[libx264 @ 000001f9d7fda240] mb P  I16..4:  1.6%  3.2%  1.4%  P16..4: 10.7%  3.2%  1.6%  0.0%  0.0%    skip:78.4%
[libx264 @ 000001f9d7fda240] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  7.6%  0.5%  0.1%  direct: 0.1%  skip:91.5%  L0:46.5% L1:52.1% BI: 1.5%
[libx264 @ 000001f9d7fda240] 8x8 transform intra:52.4% inter:85.5%
[libx264 @ 000001f9d7fda240] coded y,u,v intra: 47.9% 22.9% 17.5% inter: 1.1% 0.3% 0.2%
[libx264 @ 000001f9d7fda240] i16 v,h,dc,p: 23% 21%  6% 50%
[libx264 @ 000001f9d7fda240] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 31% 22% 14%  6%  4%  6%  4%  7%  6%
[libx264 @ 000001f9d7fda240] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 19% 13%  7%  6%  8%  5%  8%  4%
[libx264 @ 000001f9d7fda240] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 000001f9d7fda240] ref P L0: 65.5%  6.1% 18.3% 10.2%
[libx264 @ 000001f9d7fda240] ref B L0: 76.0% 21.1%  3.0%
[libx264 @ 000001f9d7fda240] ref B L1: 95.8%  4.2%
[libx264 @ 000001f9d7fda240] kb/s:196.47
[aac @ 000001f9d7a585c0] Qavg: 407.877
Cleaning up cache directory: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmpy65_boll
Cleaning up cache directory: C:\Users\REDACTED\AppData\Local\Temp\video2x\tmp4nmeeyqt
[+] INFO: Program completed, taking 251.68042 seconds

C:\Users\REDACTED\Desktop\video2x-2.7.0-win32-full>```

this is the entire cmd

**Comment by k4yt3x** [comment]
If you set `preserve_frames` to `true` in the config file and look into the temp folders, you would find a file called "no_audio.mp4". Does that file contain correct video?

**Comment by Ciellent** [comment]
Unfortunately, it does not. The no_audio.mp4 also seems to be broken as it's length is 19 seconds but it never plays and is still just black.

**Comment by k4yt3x** [comment]
Interesting. Either something's wrong when the frames are being extracted, or when the frames are being pressed back into a video. Do the frames in the temp folders look normal?

**Comment by Ciellent** [comment]
Yes they do and look absolutely amazing, it is strange that the frames here are normal but the finalized video is just black.

**Comment by Ciellent** [comment]
I guess what I can do is compile all these frames together in blender and manually add the audio until the issue is fixed.

**Comment by k4yt3x** [comment]
Is it possible for you to send the video over so I can test it?

**Comment by Ciellent** [comment]
Sure, [https://drive.google.com/open?id=1IZDM8EMmCH8GS6uxLMqdDu8xDZr-JbA3](url)

**Comment by k4yt3x** [comment]
Wait so this is the file which I provided.
Then it should work just fine.

**Comment by k4yt3x** [comment]
I think it might be more of a problem with your setup.
Also, try using the newst version.

**Comment by Ciellent** [comment]
I re-downloaded the latest version but it is still just black. It probably may be just an issue with my setup.

Here are my specs:
https://imgur.com/ekjAvaS

**Comment by k4yt3x** [comment]
Are you running 2.7.1?

**Comment by Ciellent** [comment]
I was using 2.7.0 from the releases page but I found the 2.7.1 version and I will use that one now and let you know if it works or not.

**Comment by Ciellent** [comment]
It still doesn't work with 2.7.1

**Comment by Urgeistenergie** [comment]
I also have the same issue. Black Video audio is fine. I had no I deas how to go on. So I gave up.

**Comment by chirsmitch** [comment]
I think I might have figured this out. Apparently ffmpeg doesnt do well encoding 4:4:4 streams. When I added the arguments -pix_fmt, yuv420p to the convert_video function and the migrate_audio_tracks_subtitles function in ffmpeg.py my video started working. I just cobbled this info together from ffmpeg troubleshooting posts, I don't actually know whats going on if someone else wants to take it from here.

**Comment by jitsuCM** [comment]
Having the same issue here. @chirsmitch could you post how exacly your arguments look like right now? I managed to get rid of the black video, but now it's only a single frame for the whole duration.

**Comment by chirsmitch** [comment]
![ffmpeg](https://user-images.githubusercontent.com/12040551/56465483-a3d61680-63c3-11e9-8da1-dbb41439d8be.PNG)

**Comment by jitsuCM** [comment]
Thanks. Unfortunately for me, this produces a still frame video, like if it wasn't properly reading the whole batch but was using only the first frame.

**Comment by k4yt3x** [comment]
@Ciellent @jitsuCM with some discussion going on in the telegram group, some found that VLC plays the video just fine.

Did you guys try playing the upscaled video via VLC?

**Comment by toolewdpersona** [comment]
@k4yt3x 
Yes it works!
Thx

**Comment by k4yt3x** [comment]
> Yes it works!

I wonder why the windows built-in player doesn't work.

**Comment by nicolaslandoni** [comment]
Hey guys, I'm having pretty much the same issue, black frames and get the images properly exported, but the end results is black video. 
Sample given on the repo and also tried my own.

**Comment by k4yt3x** [comment]
@nicolaslandoni does VLC play the video correctly?

**Comment by nicolaslandoni** [comment]
@k4yt3x nope, I've seen the static images being generated properly so the issue seems to be putting the video back together, I grabbed the output video and tried a couple of other programs to try analyze the video but handbrake freaks out. Audio is fine though.

**Comment by jitsuCM** [comment]
@nicolaslandoni @k4yt3x I can also confirm that the ffmpeg decomposition + video2x  waifu upscaling is properly generating the image batches, and the images seem fine.

**Comment by nicolaslandoni** [comment]
It seems to be a common issue with ffmpeg swapping the encoding options might solve the issue, will check in a couple of hours playing around with it.

**Comment by nicolaslandoni** [comment]
I was trying with diff options without luck, though forcing '-pix_fmt', 'yuv420p', improved a little since windows explorer at least shows you a thumbnail.

I find particular funny that the video track is longer than the overall expected length on the file metadta.

![Capture-Sample](https://user-images.githubusercontent.com/1806963/56587645-40f9a080-65b8-11e9-8001-5133bd455a47.PNG)

![Capture-Sample-X2](https://user-images.githubusercontent.com/1806963/56587644-40f9a080-65b8-11e9-8d18-b90df14d7bf3.PNG)

**Comment by jitsuCM** [comment]
@nicolaslandoni It's right in the Video stream metadata of the converted file:
`Duration 34ms`

Which is around an equivalent of one frame. So it's basically an audio clip =]

Somehow the -i % is not being recognized properly?

**Comment by k4yt3x** [comment]
That's sooo strange. What footage are you guys using? It might just be an encoding issue?

Does it work if the input video is mp4 h264?

**Comment by nicolaslandoni** [comment]
I've being testing with the sample provided https://files.flexio.org/Resources/Videos/sample_input.mp4 and also my own, getting pretty much the same result, videos tracks of a few ms running on 2.7.1

**Comment by nicolaslandoni** [comment]
OK, I saw that the frames being extracted weren't in proper sequence, like it was skipping one frame, checked the other folder and some of the images weren't up-scaled. So as a test run the thing as single thread and worked just fine.

**Comment by Ciellent** [comment]
@k4yt3x i can confirm the vlc media player works and displays the video perfectly. The video has audio and looks much better.

**Comment by Ciellent** [comment]
Thank you very much you saved me a lot of time

**Comment by k4yt3x** [comment]
@nicolaslandoni just to make sure, VLC doesn't play the output video?

**Comment by k4yt3x** [comment]
@Ciellent np. glad it works, though it looks like it didn't work for everybody.

**Comment by toolewdpersona** [comment]
@k4yt3x 
First I started using VLC as you recommended.
But later I was able to deal with ffmpeg.py
And now I have the output video is obtained without artifacts (not black) and is played in a normal player 
MPC-HС
All you had to do was add these values.
> 
> 
> ![ffmpeg](https://user-images.githubusercontent.com/12040551/56465483-a3d61680-63c3-11e9-8da1-dbb41439d8be.PNG)

**Comment by nicolaslandoni** [comment]
@k4yt3x after running the process as a single thread worked for me, it wasn't an encoding issue rather more like a how the threads were exploding the original video frames in folders and then the upscaler wasn't doing its job. As a result was not all the frames where they were supposed to be and creating the video from frames was bailing out, hence the empty video track.

**Comment by k4yt3x** [comment]
@toolewdpersona 

The pixel format argument should be passed on to the command from the configuration file:

![image](https://user-images.githubusercontent.com/21986859/56859036-10688c80-6953-11e9-916d-075f762b34f2.png)

Maybe what I need to do is to add the same arguments for the track migration step?
Does it work if you add this line in `video2x.json`?

![image](https://user-images.githubusercontent.com/21986859/56859044-34c46900-6953-11e9-8285-2c118b9219b1.png)

**Comment by k4yt3x** [comment]
@nicolaslandoni do the number of upscaled frames match the number of extracted frames?

**Comment by toolewdpersona** [comment]
@k4yt3x 
I returned the file to the original state ffmpeg.py
then started experimenting with video2x.json
Added one line "-pix_fmt": "yuv420p", (not work)
![v1](https://user-images.githubusercontent.com/49842912/56861479-bcd55d80-69a9-11e9-82d1-e4f14b309d19.png)
Did everything as in the screenshot (not work)
![v2,png](https://user-images.githubusercontent.com/49842912/56861435-5ea87a80-69a9-11e9-9b98-b5524d33cf7f.png)

**Comment by nicolaslandoni** [comment]
@k4yt3x while in multithreading  ( was running 2 threads ) only half of the extracted images were getting upscaled, so when the video composition was going to get executed only half of the frames were present, so process bailed out without error, resulting an empty black video.

**Comment by k4yt3x** [comment]
@nicolaslandoni that could mean that one of the threads ran out of memory and failed.

**Comment by k4yt3x** [comment]
@toolewdpersona 

Arguments seems to be passed on just fine.

![image](https://user-images.githubusercontent.com/21986859/56869154-e2bf2a00-69ca-11e9-9def-cb74c4a52110.png)

**Comment by nicolaslandoni** [comment]
@k4yt3x ok, man that would be heavy cuz it's running on hardware that by no means means is low end. 16GB or ram and 11 GB Vram

**Comment by k4yt3x** [comment]
@nicolaslandoni that hardware configuration sounds fine for more threads. If you watch the logs carefully, you might be able to see where waifu2x fails and what it says.

waifu2x-caffe doesn't come with native support for multithreading, implementing it with Python isn't as stable and reliable. If you're interested, do a test to see if multithreading actually speeds waifu2x-caffe up.

In contrast, waifu2x-converter-cpp comes with native support for multithreading. Therefore, if you set `--threads` with waifu2x-converter-cpp, you should get a faster yet more stable experience, though it doesn't have CUDNN support or much models available.

**Comment by toolewdpersona** [comment]
@k4yt3x
Yes, I checked the console and I have the same arguments as you have. But the video refuses to start normally, without these parameters "'-pix_fmt', 'yuv420p'," in ffmpeg.py itself
But I am quite satisfied with this option.

**Comment by k4yt3x** [comment]
@toolewdpersona does it work if you **remove**`shell=True` in ffmepg.py line 147?

![image](https://user-images.githubusercontent.com/21986859/56870459-a5b06300-69dd-11e9-8603-a41ab1f10b3b.png)

**Comment by k4yt3x** [comment]
I might actually know why this is the case.
With the current method of passing on arguments, we get:

```
ffmpeg -r framerate -s resolution -i video_in video_out -pix_fmt yuv420p
```

I believe we need to move the pixle format option before the output video, something like:

```
ffmpeg -r framerate -s resolution -pix_fmt yuv420p -i video_in video_out
```

**Comment by k4yt3x** [comment]
@Ciellent @toolewdpersona could you please check if this build works?

[video2x.zip](https://github.com/k4yt3x/video2x/files/3145107/video2x.zip)

**Comment by cr08** [comment]
Just adding in that I ran into this too recently after syncing my fork back up to upstream. Seemed without the pix_fmt argument added in it was trying to encode to 4:4:4 by default at least with my config. Adding that in seemed to sort it.

I'm also running into an oddity where my filesizes are way off and libx264 options as reported by mediainfo are off as well despite the same ffmpeg arguments being passed as before. I'll post a separate issue for this though.

**Comment by k4yt3x** [comment]
@cr08 does the above fix work for you?

**Comment by Ciellent** [comment]
@k4yt3x that video2x works and plays the video perfectly fine with the built-in Windows 10 media player, I think you've fixed it.

**Comment by k4yt3x** [comment]
@Ciellent perfect. I'll push the update then.

**Comment by k4yt3x** [comment]
The issue should now be fixed by commit: https://github.com/k4yt3x/video2x/commit/146044505b845224c67c5316580a283f47bd91e8

**Comment by cr08** [comment]
> @cr08 does the above fix work for you?

It did fix it for me, yes.

**Comment by arthurreckel** [comment]
I'm using the GUI and it still dont work for me. I tried changing the pixel formats but it still turns out black. I open the folder where it extract the frames and at first it was extracting well, i could see every frame, but after sometime other process started (I dont know the right words, I'm sorry ) and other folder started to be filled with black frames and the normal ones turned into black too. I dont know what to do
